/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CityBank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Work
 */
public class ManageTransactions extends javax.swing.JFrame {

    /**
     * Creates new form ManageTransactions
     */
    public ManageTransactions() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        WDPanel.setVisible(true);
        DMPanel.setVisible(false);

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        WDPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        showBalance = new javax.swing.JLabel();
        btnfind = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnWD = new javax.swing.JButton();
        showBalance3 = new javax.swing.JTextField();
        btnCNcancel = new javax.swing.JButton();
        btnWDMoney = new javax.swing.JButton();
        btnDMoney = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        DMPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAccNo2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnDM2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtAmount2 = new javax.swing.JTextField();
        btnDeposit = new javax.swing.JButton();
        showBalance2 = new javax.swing.JTextField();
        btnCNcancel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kGradientPanel1FocusGained(evt);
            }
        });

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 102, 204));
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 50, 96));

        WDPanel.setBackground(new java.awt.Color(0, 50, 96));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Withdraw Money");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your Account Number :");

        txtAccNo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Your Current Balance :");

        showBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showBalance.setForeground(new java.awt.Color(255, 255, 255));

        btnfind.setBackground(new java.awt.Color(0, 29, 66));
        btnfind.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnfind.setForeground(new java.awt.Color(255, 255, 255));
        btnfind.setText("Find");
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Amount :");

        txtAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAmountFocusLost(evt);
            }
        });
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        btnWD.setBackground(new java.awt.Color(0, 29, 66));
        btnWD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnWD.setForeground(new java.awt.Color(255, 255, 255));
        btnWD.setText("Withdraw");
        btnWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWDActionPerformed(evt);
            }
        });

        showBalance3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnCNcancel.setBackground(new java.awt.Color(0, 29, 66));
        btnCNcancel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCNcancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCNcancel.setText("Cancel");
        btnCNcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCNcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WDPanelLayout = new javax.swing.GroupLayout(WDPanel);
        WDPanel.setLayout(WDPanelLayout);
        WDPanelLayout.setHorizontalGroup(
            WDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WDPanelLayout.createSequentialGroup()
                .addGroup(WDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(WDPanelLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(showBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(WDPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(WDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WDPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(WDPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAccNo))))
                    .addGroup(WDPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(WDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showBalance3, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(txtAmount)))
                    .addGroup(WDPanelLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(WDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(WDPanelLayout.createSequentialGroup()
                                .addComponent(btnWD, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCNcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        WDPanelLayout.setVerticalGroup(
            WDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WDPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(WDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showBalance3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWD)
                    .addComponent(showBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCNcancel))
                .addGap(21, 21, 21))
        );

        btnWDMoney.setBackground(new java.awt.Color(0, 76, 133));
        btnWDMoney.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnWDMoney.setText("Withdraw Money");
        btnWDMoney.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWDMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWDMoneyActionPerformed(evt);
            }
        });

        btnDMoney.setBackground(new java.awt.Color(51, 51, 51));
        btnDMoney.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDMoney.setText("Deposit Money");
        btnDMoney.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMoneyActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(0, 102, 153));
        btnClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_30px.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        DMPanel.setBackground(new java.awt.Color(0, 50, 96));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Deposit Money");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Your Account Number :");

        txtAccNo2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtAccNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccNo2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Your Current Balance :");

        btnDM2.setBackground(new java.awt.Color(0, 29, 66));
        btnDM2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDM2.setForeground(new java.awt.Color(255, 255, 255));
        btnDM2.setText("Find");
        btnDM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDM2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Amount :");

        txtAmount2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAmount2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAmount2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAmount2FocusLost(evt);
            }
        });
        txtAmount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmount2ActionPerformed(evt);
            }
        });

        btnDeposit.setBackground(new java.awt.Color(0, 29, 66));
        btnDeposit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDeposit.setForeground(new java.awt.Color(255, 255, 255));
        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        showBalance2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        showBalance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBalance2ActionPerformed(evt);
            }
        });

        btnCNcancel1.setBackground(new java.awt.Color(0, 29, 66));
        btnCNcancel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCNcancel1.setForeground(new java.awt.Color(255, 255, 255));
        btnCNcancel1.setText("Cancel");
        btnCNcancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCNcancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DMPanelLayout = new javax.swing.GroupLayout(DMPanel);
        DMPanel.setLayout(DMPanelLayout);
        DMPanelLayout.setHorizontalGroup(
            DMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DMPanelLayout.createSequentialGroup()
                .addGroup(DMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DMPanelLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DMPanelLayout.createSequentialGroup()
                        .addGroup(DMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DMPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(DMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(DMPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(DMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DMPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(21, 21, 21)
                                            .addComponent(txtAccNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(DMPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(showBalance2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(DMPanelLayout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(btnDM2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(DMPanelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCNcancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DMPanelLayout.setVerticalGroup(
            DMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DMPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAccNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showBalance2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDM2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtAmount2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCNcancel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(btnWDMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnClose))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(DMPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addComponent(WDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(159, Short.MAX_VALUE)))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWDMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DMPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(WDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(105, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMoneyActionPerformed
        // TODO add your handling code here:
        DMPanel.setVisible(true);
        WDPanel.setVisible(false);
        

        btnDMoney.setBackground(new java.awt.Color(0, 76, 133));
        btnWDMoney.setBackground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_btnDMoneyActionPerformed

    private void btnWDMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWDMoneyActionPerformed
        // TODO add your handling code here:
        WDPanel.setVisible(true);
        DMPanel.setVisible(false);

        btnWDMoney.setBackground(new java.awt.Color(0, 76, 133));
        btnDMoney.setBackground(new java.awt.Color(51, 51, 51));
        
    }//GEN-LAST:event_btnWDMoneyActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        // TODO add your handling code here:
        IdentifiybalanceWithdraw();
    }//GEN-LAST:event_btnfindActionPerformed

    private void txtAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountFocusGained

    private void txtAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountFocusLost

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnWDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWDActionPerformed
        Withdraw();
    }//GEN-LAST:event_btnWDActionPerformed

    private void btnDM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDM2ActionPerformed
        // TODO add your handling code here:
        IdentifiybalanceDeposit();
    }//GEN-LAST:event_btnDM2ActionPerformed

    private void txtAmount2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmount2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmount2FocusGained

    private void txtAmount2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmount2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmount2FocusLost

    private void txtAmount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmount2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmount2ActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        Deposit();
        
    }//GEN-LAST:event_btnDepositActionPerformed

    private void kGradientPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kGradientPanel1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_kGradientPanel1FocusGained

    private void txtAccNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccNo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccNo2ActionPerformed

    private void showBalance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBalance2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showBalance2ActionPerformed

    private void btnCNcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCNcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCNcancelActionPerformed

    private void btnCNcancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCNcancel1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCNcancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTransactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DMPanel;
    private javax.swing.JPanel WDPanel;
    private javax.swing.JButton btnCNcancel;
    private javax.swing.JButton btnCNcancel1;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDM2;
    private javax.swing.JButton btnDMoney;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnWD;
    private javax.swing.JButton btnWDMoney;
    private javax.swing.JButton btnfind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel showBalance;
    private javax.swing.JTextField showBalance2;
    private javax.swing.JTextField showBalance3;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtAccNo2;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAmount2;
    // End of variables declaration//GEN-END:variables

    private void IdentifiybalanceDeposit() {
        Connection dbconn = DBConnection.connectDB();
        if(dbconn != null){
        try {
            PreparedStatement st = (PreparedStatement)dbconn.prepareStatement("Select * from customersdb WHERE accountnumber  = ?");
            
            int id = (Integer.parseInt(txtAccNo2.getText()));           
            st.setInt(1, id);
            ResultSet res = st.executeQuery();
            
            if(res.next()==false) {
                JOptionPane.showMessageDialog(this, "Sorry Record Not Found");
                showBalance2.setText("");
                
                txtAccNo2.requestFocus();
            } else {               
                
                showBalance2.setText(res.getString("depositamount"));
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SearchDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Sorry, Record Not Found.", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        } else {
            System.out.println("The Connection not available");
        }
    }
    
    private void IdentifiybalanceWithdraw() {
        Connection dbconn = DBConnection.connectDB();
        if(dbconn != null){
        try {
            PreparedStatement st = (PreparedStatement)dbconn.prepareStatement("Select * from customersdb WHERE accountnumber  = ?");
            
            int id = (Integer.parseInt(txtAccNo.getText()));           
            st.setInt(1, id);
            ResultSet res = st.executeQuery();
            
            if(res.next()==false) {
                JOptionPane.showMessageDialog(this, "Sorry Record Not Found");
                showBalance3.setText("");
                
                txtAccNo.requestFocus();
            } else {               
 
                showBalance3.setText(res.getString("depositamount"));
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SearchDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Sorry, Record Not Found.", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        } else {
            System.out.println("The Connection not available");
        }
    }

    
    private void Deposit(){
        
        String amount = txtAmount2.getText();
        String Lbal = showBalance2.getText();
        String AccNum = txtAccNo2.getText();
        
        double num1 = Double.parseDouble(amount);
        double num2 = Double.parseDouble(Lbal);
        
        double Finaly = num1 + num2;
        
        String Final = Double.toString(Finaly);
        
        Connection dbconn = DBConnection.connectDB();
        if(dbconn != null){
            
            try {
            
            PreparedStatement st = (PreparedStatement)dbconn.prepareStatement("Select * from customersdb WHERE accountnumber  = '"+AccNum+"'");
            ResultSet res1 = st.executeQuery();
            st.executeUpdate("update customersdb set depositamount='"+Final+"' where accountnumber='"+AccNum+"'");
            JOptionPane.showMessageDialog(this, "Money Deposited.", "Sucess", JOptionPane.INFORMATION_MESSAGE);     
            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(ManageTransactions.class.getName()).log(Level.SEVERE, null, ex);
        }
       } 
      }  
    
    private void Withdraw(){
        
        String amount = txtAmount.getText();
        String Lbal = showBalance3.getText();
        String AccNum = txtAccNo.getText();
        
        double num1 = Double.parseDouble(amount);
        double num2 = Double.parseDouble(Lbal);
        
        double Finaly = num2 - num1;
        
        String Final = Double.toString(Finaly);
        
        Connection dbconn = DBConnection.connectDB();
        if(dbconn != null){
            
            try {
            
            PreparedStatement st = (PreparedStatement)dbconn.prepareStatement("Select * from customersdb WHERE accountnumber  = '"+AccNum+"'");
            ResultSet res1 = st.executeQuery();
            st.executeUpdate("update customersdb set depositamount='"+Final+"' where accountnumber='"+AccNum+"'");
            JOptionPane.showMessageDialog(this, "Money Withdrawed", "Sucess", JOptionPane.INFORMATION_MESSAGE);     
            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(ManageTransactions.class.getName()).log(Level.SEVERE, null, ex);
        }
       } 
      }

}
